#
# COPYRIGHT Ericsson 2021
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

version: 3

server: https://scasfossa.internal.ericsson.com

project:
  id: eric-oss-core-reporting-dimension-query
  name: eric-oss-core-reporting-dimension-query
  team: eric-oss-vibranium

paths:
  only:
    - ./
  exclude:
    - batteries/

targets:
  only:
    - type: maven
      path: ./
      target: 'com.ericsson.oss.air:eric-oss-core-reporting-dimension-query'
    - type: maven
      path: ./
      target: 'com.ericsson.oss.air:eric-oss-core-reporting-dimension-query-main'
    - type: maven
      path: ./
      target: 'com.ericsson.oss.air:eric-oss-core-reporting-dimension-query-security'
  exclude:
    - type: maven
      path: ./
      target: 'com.ericsson.oss.air:eric-oss-core-reporting-dimension-query-cts-stubs'
