#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-oss-core-reporting-dimension-query.name" . }}-ath-query-config
  labels:
  {{- include "eric-oss-core-reporting-dimension-query.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-core-reporting-dimension-query.annotations-and-prometheus" . | nindent 4 }}
data:
  {{- (.Files.Glob "config/queries/**.yaml").AsConfig | nindent 2 }}

