#
# COPYRIGHT Ericsson 2024
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#
{{- $derivedKeystorePassword := derivePassword 1 "long" ( include "eric-oss-core-reporting-dimension-query.name" . ) "tls-keystore-password" .Release.Namespace -}}
{{- $derivedKeystoreKeyPassword := derivePassword 1 "long" ( include "eric-oss-core-reporting-dimension-query.name" . ) "tls-keystore-key-password" .Release.Namespace -}}
{{- $tls := include "eric-oss-core-reporting-dimension-query.cardq-security-tls-enabled" . | trim -}}
{{- if  (eq $tls "true") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eric-oss-core-reporting-dimension-query.name" . }}-tls-keystore-secret
  labels:
  {{- include "eric-oss-core-reporting-dimension-query.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-oss-core-reporting-dimension-query.annotations" . | nindent 4 }}
    helm.sh/resource-policy: {{ .Values.secret.keystore.resourcePolicy }}
type: Opaque
data:
  password: {{ $derivedKeystorePassword | b64enc | quote }}
  keyPassword: {{ $derivedKeystoreKeyPassword | b64enc | quote }}
{{- end }}