#
# COPYRIGHT Ericsson 2023
#
#
#
# The copyright to the computer program(s) herein is the property of
#
# Ericsson Inc. The programs may be used and/or copied only with written
#
# permission from Ericsson Inc. or in accordance with the terms and
#
# conditions stipulated in the agreement/contract under which the
#
# program(s) have been supplied.
#

documents:
  # document name
  - name: user_guide
    # file names of files to be packaged in the document
    files:
      - ../doc/User_Guide/User_Guide.md
      - ../doc/User_Guide/CARDQ_architecture_overview.png
      - ../doc/User_Guide/CARDQ_deployment_overview.png
      - ../doc/User_Guide/CARDQ_architecture_overview_with_neo4j.png
  - name: developers_guide
    files:
      - ../doc/Application_Developers_Guide/Application_Developers_Guide.md
      - ../doc/Application_Developers_Guide/cardq-system-context-view.png
      - ../doc/Application_Developers_Guide/cardq-application-integration.png
