:begin
CREATE CONSTRAINT amf_uuid FOR (node:amf) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT cismcluster_uuid FOR (node:cismcluster) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT fiveqiflow_uuid FOR (node:fiveqiflow) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT fiveqiset_uuid FOR (node:fiveqiset) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT geographicsite_uuid FOR (node:geographicsite) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT gnbdu_uuid FOR (node:gnbdu) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT networkslice_uuid FOR (node:networkslice) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT networkslicesubnet_uuid FOR (node:networkslicesubnet) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT nrcell_uuid FOR (node:nrcell) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT plmninfo_uuid FOR (node:plmninfo) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT qosprofile_uuid FOR (node:qosprofile) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT resourcepartition_uuid FOR (node:resourcepartition) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT resourcepartitionmember_uuid FOR (node:resourcepartitionmember) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT resourcepartitionset_uuid FOR (node:resourcepartitionset) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT serviceprofile_uuid FOR (node:serviceprofile) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT sliceprofile_uuid FOR (node:sliceprofile) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT smf_uuid FOR (node:smf) REQUIRE (node.uuid) IS UNIQUE;
CREATE CONSTRAINT upf_uuid FOR (node:upf) REQUIRE (node.uuid) IS UNIQUE;
:commit
CALL db.awaitIndexes(300);
:begin
UNWIND [{uuid:"ctw/nrcell/285599", properties:{name:"N8/NRCell:NRC-B"}}, {uuid:"ctw/nrcell/285619", properties:{name:"N9/NRCell:NRC-B"}}, {uuid:"ctw/nrcell/285636", properties:{name:"N13/NRCell:NRC-A", trackingAreaCode:"809"}}, {uuid:"ctw/nrcell/285656", properties:{name:"N14/NRCell:NRC-A", trackingAreaCode:"809"}}, {uuid:"ctw/nrcell/251546", properties:{name:"N81/NRCell:NRC-A", trackingAreaCode:"732763"}}, {uuid:"ctw/nrcell/251525", properties:{name:"N209/NRCell:NRC-A", trackingAreaCode:"999"}}, {uuid:"ctw/nrcell/251524", properties:{name:"N2009/NRCell:NRC-A", trackingAreaCode:"999"}}] AS row
CREATE (n:nrcell{uuid: row.uuid}) SET n += row.properties SET n:resource:ctw;
UNWIND [{uuid:"ctw/smf/21330", properties:{ExternalRef_nodeFDN:"MeContext=PCC00020,ManagedElement=PCC00020", SOA_NF_nfFqdn:"pcc00020.sero.gic.ericsson.se", SOA_NF_applicationId:"PCC00020", name:"WirelessNetworkFunction:PCC00020-SMF", SOA_NF_oamIP:"10.120.130.20", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7120"}}, {uuid:"ctw/smf/21331", properties:{ExternalRef_nodeFDN:"MeContext=PCC00021,ManagedElement=PCC00021", SOA_NF_nfFqdn:"pcc00021.sero.gic.ericsson.se", SOA_NF_applicationId:"PCC00021", name:"WirelessNetworkFunction:PCC00021-SMF", SOA_NF_oamIP:"10.120.130.21", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7121"}}, {uuid:"ctw/smf/21332", properties:{ExternalRef_nodeFDN:"MeContext=PCC00022,ManagedElement=PCC00022", SOA_NF_nfFqdn:"pcc00022.sero.gic.ericsson.se", SOA_NF_applicationId:"PCC00022", name:"WirelessNetworkFunction:PCC00022-SMF", SOA_NF_oamIP:"10.120.130.22", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7122"}}] AS row
CREATE (n:smf{uuid: row.uuid}) SET n += row.properties SET n:ctw:wirelessNetworkFunction;
UNWIND [{uuid:"ctw/upf/21333", properties:{ExternalRef_nodeFDN:"MeContext=PCG00030,ManagedElement=PCC00030", SOA_NF_nfFqdn:"pcg00030.sero.gic.ericsson.se", SOA_NF_applicationId:"PCG00030", name:"WirelessNetworkFunction:PCG00030-UPF", SOA_NF_oamIP:"10.120.130.30", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7130"}}, {uuid:"ctw/upf/21335", properties:{ExternalRef_nodeFDN:"MeContext=PCG00032,ManagedElement=PCC00032", SOA_NF_nfFqdn:"pcg00032.sero.gic.ericsson.se", SOA_NF_applicationId:"PCG00032", name:"WirelessNetworkFunction:PCG00032-UPF", SOA_NF_oamIP:"10.120.130.32", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7131"}}, {uuid:"ctw/upf/21334", properties:{ExternalRef_nodeFDN:"MeContext=PCG00031,ManagedElement=PCC00031", SOA_NF_nfFqdn:"pcg00031.sero.gic.ericsson.se", SOA_NF_applicationId:"PCG00031", name:"WirelessNetworkFunction:PCG00031-UPF", SOA_NF_oamIP:"10.120.130.31", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7131"}}] AS row
CREATE (n:upf{uuid: row.uuid}) SET n += row.properties SET n:ctw:wirelessNetworkFunction;
UNWIND [{uuid:"ctw/networkslicesubnet/21318", properties:{name:"NetworkSliceSubnet:NSSI-A1"}}, {uuid:"ctw/networkslicesubnet/21320", properties:{name:"NetworkSliceSubnet:NSSI-C1"}}, {uuid:"ctw/networkslicesubnet/21322", properties:{name:"NetworkSliceSubnet:NSSI-A12"}}, {uuid:"ctw/networkslicesubnet/21324", properties:{name:"NetworkSliceSubnet:NSSI-B12"}}, {uuid:"ctw/networkslicesubnet/21326", properties:{name:"NetworkSliceSubnet:NSSI-C12"}}, {uuid:"ctw/networkslicesubnet/21319", properties:{name:"NetworkSliceSubnet:NSSI-B1"}}, {uuid:"ctw/networkslicesubnet/21321", properties:{name:"NetworkSliceSubnet:NSSI-A11"}}, {uuid:"ctw/networkslicesubnet/21323", properties:{name:"NetworkSliceSubnet:NSSI-B11"}}, {uuid:"ctw/networkslicesubnet/21325", properties:{name:"NetworkSliceSubnet:NSSI-C11"}}, {uuid:"ctw/networkslicesubnet/21327", properties:{name:"NetworkSliceSubnet:NSSI-C13"}}, {uuid:"ctw/networkslicesubnet/285604", properties:{name:"N8/NetworkSliceSubnet:NSSI-B2"}}, {uuid:"ctw/networkslicesubnet/285606", properties:{name:"N8/NetworkSliceSubnet:NSSI-B4"}}, {uuid:"ctw/networkslicesubnet/285603", properties:{name:"N8/NetworkSliceSubnet:NSSI-B1"}}, {uuid:"ctw/networkslicesubnet/285605", properties:{name:"N8/NetworkSliceSubnet:NSSI-B3"}}, {uuid:"ctw/networkslicesubnet/285626", properties:{name:"N9/NetworkSliceSubnet:NSSI-B2"}}, {uuid:"ctw/networkslicesubnet/285625", properties:{name:"N9/NetworkSliceSubnet:NSSI-B1"}}, {uuid:"ctw/networkslicesubnet/285627", properties:{name:"N9/NetworkSliceSubnet:NSSI-B3"}}, {uuid:"ctw/networkslicesubnet/285628", properties:{name:"N9/NetworkSliceSubnet:NSSI-B4"}}, {uuid:"ctw/networkslicesubnet/285629", properties:{name:"N9/NetworkSliceSubnet:NSSI-B5"}}, {uuid:"ctw/networkslicesubnet/285630", properties:{name:"N9/NetworkSliceSubnet:NSSI-B6"}}] AS row
CREATE (n:networkslicesubnet{uuid: row.uuid}) SET n += row.properties SET n:ctw:logicalPartition;
UNWIND [{uuid:"ctw/networkslicesubnet/285639", properties:{name:"N13/NetworkSliceSubnet:NSSI-B"}}, {uuid:"ctw/networkslicesubnet/285641", properties:{name:"N13/NetworkSliceSubnet:NSSI-A"}}, {uuid:"ctw/networkslicesubnet/285640", properties:{name:"N13/NetworkSliceSubnet:NSSI-C"}}, {uuid:"ctw/networkslicesubnet/285660", properties:{name:"N14/NetworkSliceSubnet:NSSI-C"}}, {uuid:"ctw/networkslicesubnet/285659", properties:{name:"N14/NetworkSliceSubnet:NSSI-B"}}, {uuid:"ctw/networkslicesubnet/285661", properties:{name:"N14/NetworkSliceSubnet:NSSI-A"}}, {uuid:"ctw/networkslicesubnet/284332", properties:{name:"NSS3212/NetworkSliceSubnet:NSSI-A"}}] AS row
CREATE (n:networkslicesubnet{uuid: row.uuid}) SET n += row.properties SET n:ctw:logicalPartition;
UNWIND [{uuid:"ctw/sliceprofile/3883", properties:{name:"SliceProfile:SP-A11"}}, {uuid:"ctw/sliceprofile/3889", properties:{name:"SliceProfile:SP-C13"}}, {uuid:"ctw/sliceprofile/3885", properties:{name:"SliceProfile:SP-B11"}}, {uuid:"ctw/sliceprofile/3887", properties:{name:"SliceProfile:SP-C11"}}, {uuid:"ctw/sliceprofile/3884", properties:{name:"SliceProfile:SP-A12"}}, {uuid:"ctw/sliceprofile/3886", properties:{name:"SliceProfile:SP-B12"}}, {uuid:"ctw/sliceprofile/3888", properties:{name:"SliceProfile:SP-C12"}}, {uuid:"ctw/sliceprofile/52687", properties:{name:"N8/SliceProfile:SP-B1"}}, {uuid:"ctw/sliceprofile/52688", properties:{name:"N8/SliceProfile:SP-B2"}}, {uuid:"ctw/sliceprofile/52690", properties:{name:"N9/SliceProfile:SP-B2"}}, {uuid:"ctw/sliceprofile/52689", properties:{name:"N9/SliceProfile:SP-B1"}}, {uuid:"ctw/sliceprofile/52691", properties:{name:"N13/SliceProfile:SP-A1"}}, {uuid:"ctw/sliceprofile/52692", properties:{name:"N13/SliceProfile:SP-A2"}}, {uuid:"ctw/sliceprofile/52693", properties:{name:"N13/SliceProfile:SP-A3"}}, {uuid:"ctw/sliceprofile/52694", properties:{name:"N13/SliceProfile:SP-A4"}}, {uuid:"ctw/sliceprofile/52695", properties:{name:"N13/SliceProfile:SP-A5"}}, {uuid:"ctw/sliceprofile/52696", properties:{name:"N13/SliceProfile:SP-A6"}}, {uuid:"ctw/sliceprofile/52697", properties:{name:"N14/SliceProfile:SP-A1"}}, {uuid:"ctw/sliceprofile/52698", properties:{name:"N14/SliceProfile:SP-A2"}}, {uuid:"ctw/sliceprofile/52699", properties:{name:"N14/SliceProfile:SP-A3"}}] AS row
CREATE (n:sliceprofile{uuid: row.uuid}) SET n += row.properties SET n:ctw:profileObject;
UNWIND [{uuid:"ctw/sliceprofile/52700", properties:{name:"N14/SliceProfile:SP-A4"}}, {uuid:"ctw/sliceprofile/52701", properties:{name:"N14/SliceProfile:SP-A5"}}, {uuid:"ctw/sliceprofile/52702", properties:{name:"N14/SliceProfile:SP-A6"}}] AS row
CREATE (n:sliceprofile{uuid: row.uuid}) SET n += row.properties SET n:ctw:profileObject;
UNWIND [{uuid:"ctw/gnbdu/285598", properties:{name:"N8/GNB-DU:B"}}, {uuid:"ctw/gnbdu/285618", properties:{name:"N9/GNB-DU:B"}}, {uuid:"ctw/gnbdu/285637", properties:{name:"N13/GNB-DU:A"}}, {uuid:"ctw/gnbdu/285657", properties:{name:"N14/GNB-DU:A"}}] AS row
CREATE (n:gnbdu{uuid: row.uuid}) SET n += row.properties SET n:ctw:wirelessNetworkFunction;
UNWIND [{uuid:"ctw/resourcepartition/285608", properties:{name:"N8/ResourcePartition:RP-B2"}}, {uuid:"ctw/resourcepartition/285610", properties:{name:"N8/ResourcePartition:RP-B4"}}, {uuid:"ctw/resourcepartition/285607", properties:{name:"N8/ResourcePartition:RP-B1"}}, {uuid:"ctw/resourcepartition/285609", properties:{name:"N8/ResourcePartition:RP-B3"}}, {uuid:"ctw/resourcepartition/285631", properties:{name:"N9/ResourcePartition:RP-B1"}}, {uuid:"ctw/resourcepartition/285632", properties:{name:"N9/ResourcePartition:RP-B2"}}, {uuid:"ctw/resourcepartition/285648", properties:{name:"N13/ResourcePartition:RP-A2"}}, {uuid:"ctw/resourcepartition/285650", properties:{name:"N13/ResourcePartition:RP-A4"}}, {uuid:"ctw/resourcepartition/285652", properties:{name:"N13/ResourcePartition:RP-A6"}}, {uuid:"ctw/resourcepartition/285647", properties:{name:"N13/ResourcePartition:RP-A1"}}, {uuid:"ctw/resourcepartition/285649", properties:{name:"N13/ResourcePartition:RP-A3"}}, {uuid:"ctw/resourcepartition/285651", properties:{name:"N13/ResourcePartition:RP-A5"}}, {uuid:"ctw/resourcepartition/285667", properties:{name:"N14/ResourcePartition:RP-A1"}}, {uuid:"ctw/resourcepartition/285669", properties:{name:"N14/ResourcePartition:RP-A3"}}, {uuid:"ctw/resourcepartition/285671", properties:{name:"N14/ResourcePartition:RP-A5"}}, {uuid:"ctw/resourcepartition/285668", properties:{name:"N14/ResourcePartition:RP-A2"}}, {uuid:"ctw/resourcepartition/285670", properties:{name:"N14/ResourcePartition:RP-A4"}}, {uuid:"ctw/resourcepartition/285672", properties:{name:"N14/ResourcePartition:RP-A6"}}] AS row
CREATE (n:resourcepartition{uuid: row.uuid}) SET n += row.properties SET n:resource:ctw;
UNWIND [{uuid:"ctw/fiveqiflow/8045", properties:{name:"N8/FiveQIFlow:FQF-B2"}}, {uuid:"ctw/fiveqiflow/8046", properties:{name:"N8/FiveQIFlow:FQF-B1"}}, {uuid:"ctw/fiveqiflow/8047", properties:{name:"N8/FiveQIFlow:FQF-B3"}}, {uuid:"ctw/fiveqiflow/8049", properties:{name:"N8/FiveQIFlow:FQF-B7"}}, {uuid:"ctw/fiveqiflow/8048", properties:{name:"N8/FiveQIFlow:FQF-B6"}}, {uuid:"ctw/fiveqiflow/8051", properties:{name:"N8/FiveQIFlow:FQF-B9"}}, {uuid:"ctw/fiveqiflow/8050", properties:{name:"N8/FiveQIFlow:FQF-B8"}}, {uuid:"ctw/fiveqiflow/8052", properties:{name:"N8/FiveQIFlow:FQF-B10"}}, {uuid:"ctw/fiveqiflow/8053", properties:{name:"N8/FiveQIFlow:FQF-B11"}}, {uuid:"ctw/fiveqiflow/8054", properties:{name:"N8/FiveQIFlow:FQF-B12"}}, {uuid:"ctw/fiveqiflow/8056", properties:{name:"N8/FiveQIFlow:FQF-B5"}}, {uuid:"ctw/fiveqiflow/8058", properties:{name:"N8/FiveQIFlow:FQF-B14"}}, {uuid:"ctw/fiveqiflow/8060", properties:{name:"N8/FiveQIFlow:FQF-B16"}}, {uuid:"ctw/fiveqiflow/8055", properties:{name:"N8/FiveQIFlow:FQF-B4"}}, {uuid:"ctw/fiveqiflow/8062", properties:{name:"N8/FiveQIFlow:FQF-B18"}}, {uuid:"ctw/fiveqiflow/8064", properties:{name:"N8/FiveQIFlow:FQF-B20"}}, {uuid:"ctw/fiveqiflow/8066", properties:{name:"N8/FiveQIFlow:FQF-B22"}}, {uuid:"ctw/fiveqiflow/8057", properties:{name:"N8/FiveQIFlow:FQF-B13"}}, {uuid:"ctw/fiveqiflow/8068", properties:{name:"N8/FiveQIFlow:FQF-B24"}}, {uuid:"ctw/fiveqiflow/8070", properties:{name:"N8/FiveQIFlow:FQF-B26"}}] AS row
CREATE (n:fiveqiflow{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/fiveqiflow/8059", properties:{name:"N8/FiveQIFlow:FQF-B15"}}, {uuid:"ctw/fiveqiflow/8061", properties:{name:"N8/FiveQIFlow:FQF-B17"}}, {uuid:"ctw/fiveqiflow/8063", properties:{name:"N8/FiveQIFlow:FQF-B19"}}, {uuid:"ctw/fiveqiflow/8065", properties:{name:"N8/FiveQIFlow:FQF-B21"}}, {uuid:"ctw/fiveqiflow/8067", properties:{name:"N8/FiveQIFlow:FQF-B23"}}, {uuid:"ctw/fiveqiflow/8069", properties:{name:"N8/FiveQIFlow:FQF-B25"}}, {uuid:"ctw/fiveqiflow/8072", properties:{name:"N9/FiveQIFlow:FQF-B1"}}, {uuid:"ctw/fiveqiflow/8074", properties:{name:"N9/FiveQIFlow:FQF-B6"}}, {uuid:"ctw/fiveqiflow/8071", properties:{name:"N9/FiveQIFlow:FQF-B2"}}, {uuid:"ctw/fiveqiflow/8076", properties:{name:"N9/FiveQIFlow:FQF-B8"}}, {uuid:"ctw/fiveqiflow/8078", properties:{name:"N9/FiveQIFlow:FQF-B10"}}, {uuid:"ctw/fiveqiflow/8073", properties:{name:"N9/FiveQIFlow:FQF-B3"}}, {uuid:"ctw/fiveqiflow/8075", properties:{name:"N9/FiveQIFlow:FQF-B7"}}, {uuid:"ctw/fiveqiflow/8080", properties:{name:"N9/FiveQIFlow:FQF-B12"}}, {uuid:"ctw/fiveqiflow/8077", properties:{name:"N9/FiveQIFlow:FQF-B9"}}, {uuid:"ctw/fiveqiflow/8082", properties:{name:"N9/FiveQIFlow:FQF-B5"}}, {uuid:"ctw/fiveqiflow/8079", properties:{name:"N9/FiveQIFlow:FQF-B11"}}, {uuid:"ctw/fiveqiflow/8084", properties:{name:"N9/FiveQIFlow:FQF-B14"}}, {uuid:"ctw/fiveqiflow/8081", properties:{name:"N9/FiveQIFlow:FQF-B4"}}, {uuid:"ctw/fiveqiflow/8083", properties:{name:"N9/FiveQIFlow:FQF-B13"}}] AS row
CREATE (n:fiveqiflow{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/fiveqiflow/8086", properties:{name:"N9/FiveQIFlow:FQF-B16"}}, {uuid:"ctw/fiveqiflow/8085", properties:{name:"N9/FiveQIFlow:FQF-B15"}}, {uuid:"ctw/fiveqiflow/8088", properties:{name:"N9/FiveQIFlow:FQF-B18"}}, {uuid:"ctw/fiveqiflow/8087", properties:{name:"N9/FiveQIFlow:FQF-B17"}}, {uuid:"ctw/fiveqiflow/8090", properties:{name:"N9/FiveQIFlow:FQF-B20"}}, {uuid:"ctw/fiveqiflow/8089", properties:{name:"N9/FiveQIFlow:FQF-B19"}}, {uuid:"ctw/fiveqiflow/8092", properties:{name:"N9/FiveQIFlow:FQF-B22"}}, {uuid:"ctw/fiveqiflow/8091", properties:{name:"N9/FiveQIFlow:FQF-B21"}}, {uuid:"ctw/fiveqiflow/8093", properties:{name:"N13/FiveQIFlow:FQF-A1"}}, {uuid:"ctw/fiveqiflow/8094", properties:{name:"N13/FiveQIFlow:FQF-A2"}}, {uuid:"ctw/fiveqiflow/8095", properties:{name:"N13/FiveQIFlow:FQF-A3"}}, {uuid:"ctw/fiveqiflow/8096", properties:{name:"N13/FiveQIFlow:FQF-A4"}}, {uuid:"ctw/fiveqiflow/8097", properties:{name:"N13/FiveQIFlow:FQF-A5"}}, {uuid:"ctw/fiveqiflow/8098", properties:{name:"N13/FiveQIFlow:FQF-A6"}}, {uuid:"ctw/fiveqiflow/8099", properties:{name:"N14/FiveQIFlow:FQF-A1"}}, {uuid:"ctw/fiveqiflow/8100", properties:{name:"N14/FiveQIFlow:FQF-A2"}}, {uuid:"ctw/fiveqiflow/8101", properties:{name:"N14/FiveQIFlow:FQF-A3"}}, {uuid:"ctw/fiveqiflow/8103", properties:{name:"N14/FiveQIFlow:FQF-A5"}}, {uuid:"ctw/fiveqiflow/8102", properties:{name:"N14/FiveQIFlow:FQF-A4"}}, {uuid:"ctw/fiveqiflow/8104", properties:{name:"N14/FiveQIFlow:FQF-A6"}}] AS row
CREATE (n:fiveqiflow{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/fiveqiflow/5034", properties:{name:"QOS64/FiveQIFlow:FQF-A2"}}, {uuid:"ctw/fiveqiflow/5033", properties:{name:"QOS64/FiveQIFlow:FQF-A1"}}] AS row
CREATE (n:fiveqiflow{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/resourcepartitionset/285616", properties:{name:"N8/ResourcePartitionSet:RPS-B2"}}, {uuid:"ctw/resourcepartitionset/285615", properties:{name:"N8/ResourcePartitionSet:RPS-B1"}}, {uuid:"ctw/resourcepartitionset/285617", properties:{name:"N8/ResourcePartitionSet:RPS-B3"}}, {uuid:"ctw/resourcepartitionset/285635", properties:{name:"N9/ResourcePartitionSet:RPS-B"}}, {uuid:"ctw/resourcepartitionset/285654", properties:{name:"N13/ResourcePartitionSet:RPS-B"}}, {uuid:"ctw/resourcepartitionset/285653", properties:{name:"N13/ResourcePartitionSet:RPS-A"}}, {uuid:"ctw/resourcepartitionset/285655", properties:{name:"N13/ResourcePartitionSet:RPS-C"}}, {uuid:"ctw/resourcepartitionset/285673", properties:{name:"N14/ResourcePartitionSet:RPS-A"}}, {uuid:"ctw/resourcepartitionset/285675", properties:{name:"N14/ResourcePartitionSet:RPS-C"}}, {uuid:"ctw/resourcepartitionset/285674", properties:{name:"N14/ResourcePartitionSet:RPS-B"}}] AS row
CREATE (n:resourcepartitionset{uuid: row.uuid}) SET n += row.properties SET n:resource:ctw;
UNWIND [{uuid:"ctv/cismcluster/21313", properties:{name:"CismCluster:DataCenter1"}}, {uuid:"ctv/cismcluster/21314", properties:{name:"CismCluster:DataCenter2"}}] AS row
CREATE (n:cismcluster{uuid: row.uuid}) SET n += row.properties SET n:ctv:controllerFunction;
UNWIND [{uuid:"ctw/fiveqiset/3306", properties:{name:"N8/FiveQISet:FQS-B2"}}, {uuid:"ctw/fiveqiset/3308", properties:{name:"N8/FiveQISet:FQS-B4"}}, {uuid:"ctw/fiveqiset/3310", properties:{name:"N8/FiveQISet:FQS-B6"}}, {uuid:"ctw/fiveqiset/3305", properties:{name:"N8/FiveQISet:FQS-B1"}}, {uuid:"ctw/fiveqiset/3307", properties:{name:"N8/FiveQISet:FQS-B3"}}, {uuid:"ctw/fiveqiset/3309", properties:{name:"N8/FiveQISet:FQS-B5"}}, {uuid:"ctw/fiveqiset/3311", properties:{name:"N8/FiveQISet:FQS-B7"}}, {uuid:"ctw/fiveqiset/3313", properties:{name:"N9/FiveQISet:FQS-B2"}}, {uuid:"ctw/fiveqiset/3312", properties:{name:"N9/FiveQISet:FQS-B1"}}, {uuid:"ctw/fiveqiset/3315", properties:{name:"N9/FiveQISet:FQS-B4"}}, {uuid:"ctw/fiveqiset/3314", properties:{name:"N9/FiveQISet:FQS-B3"}}, {uuid:"ctw/fiveqiset/3316", properties:{name:"N9/FiveQISet:FQS-B5"}}, {uuid:"ctw/fiveqiset/3318", properties:{name:"N13/FiveQISet:FQS-B"}}, {uuid:"ctw/fiveqiset/3317", properties:{name:"N13/FiveQISet:FQS-A"}}, {uuid:"ctw/fiveqiset/3319", properties:{name:"N13/FiveQISet:FQS-C"}}, {uuid:"ctw/fiveqiset/3320", properties:{name:"N14/FiveQISet:FQS-A"}}, {uuid:"ctw/fiveqiset/3322", properties:{name:"N14/FiveQISet:FQS-C"}}, {uuid:"ctw/fiveqiset/3321", properties:{name:"N14/FiveQISet:FQS-B"}}, {uuid:"ctw/fiveqiset/2143", properties:{name:"QOS64/FiveQISet:FQS-A2"}}, {uuid:"ctw/fiveqiset/2142", properties:{name:"QOS64/FiveQISet:FQS-A1"}}] AS row
CREATE (n:fiveqiset{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/plmninfo/3828", properties:{sNSSAI_SST:"1", plmn_mcc:"100", name:"PlmnInfo:100-101|1-1", sNSSAI_SD:"1", plmn_mnc:"101"}}, {uuid:"ctw/plmninfo/3830", properties:{sNSSAI_SST:"5", plmn_mcc:"100", name:"PlmnInfo:100-101|1-5", sNSSAI_SD:"1", plmn_mnc:"101"}}, {uuid:"ctw/plmninfo/3832", properties:{sNSSAI_SST:"9", plmn_mcc:"100", name:"PlmnInfo:100-101|3-9", sNSSAI_SD:"3", plmn_mnc:"101"}}, {uuid:"ctw/plmninfo/3831", properties:{sNSSAI_SST:"9", plmn_mcc:"100", name:"PlmnInfo:100-101|1-9", sNSSAI_SD:"1", plmn_mnc:"101"}}, {uuid:"ctw/plmninfo/3833", properties:{sNSSAI_SST:"83", plmn_mcc:"100", name:"PlmnInfo:100-101|5-83", sNSSAI_SD:"5", plmn_mnc:"101"}}, {uuid:"ctw/plmninfo/3829", properties:{sNSSAI_SST:"3", plmn_mcc:"100", name:"PlmnInfo:100-101|1-3", sNSSAI_SD:"1", plmn_mnc:"101"}}, {uuid:"ctw/plmninfo/55887", properties:{sNSSAI_SST:"2", plmn_mcc:"460", name:"N8/PlmnInfo:PLMNI-B1", sNSSAI_SD:"3", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55889", properties:{sNSSAI_SST:"1", plmn_mcc:"460", name:"N8/PlmnInfo:PLMNI-B2", sNSSAI_SD:"1", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55886", properties:{sNSSAI_SST:"1", plmn_mcc:"460", name:"N8/PlmnInfo:PLMNI-B4", sNSSAI_SD:"3", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55888", properties:{sNSSAI_SST:"1", plmn_mcc:"460", name:"N8/PlmnInfo:PLMNI-B3", sNSSAI_SD:"2", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55890", properties:{sNSSAI_SST:"1", plmn_mcc:"460", name:"N9/PlmnInfo:PLMNI-B4", sNSSAI_SD:"3", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55891", properties:{sNSSAI_SST:"2", plmn_mcc:"460", name:"N9/PlmnInfo:PLMNI-B1", sNSSAI_SD:"3", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55892", properties:{sNSSAI_SST:"1", plmn_mcc:"460", name:"N9/PlmnInfo:PLMNI-B3", sNSSAI_SD:"2", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55893", properties:{sNSSAI_SST:"1", plmn_mcc:"460", name:"N9/PlmnInfo:PLMNI-B2", sNSSAI_SD:"1", plmn_mnc:"08"}}, {uuid:"ctw/plmninfo/55895", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A9", sNSSAI_SD:"9", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55897", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A7", sNSSAI_SD:"7", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55894", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A10", sNSSAI_SD:"10", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55899", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A5", sNSSAI_SD:"5", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55896", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A8", sNSSAI_SD:"8", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55901", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A3", sNSSAI_SD:"3", plmn_mnc:"81"}}] AS row
CREATE (n:plmninfo{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/plmninfo/55898", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A6", sNSSAI_SD:"6", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55903", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A1", sNSSAI_SD:"1", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55900", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A4", sNSSAI_SD:"4", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55905", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A30", sNSSAI_SD:"30", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55907", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A28", sNSSAI_SD:"28", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55902", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A2", sNSSAI_SD:"2", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55909", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A26", sNSSAI_SD:"26", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55904", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A0", sNSSAI_SD:"0", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55911", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A24", sNSSAI_SD:"24", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55906", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A29", sNSSAI_SD:"29", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55913", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A22", sNSSAI_SD:"22", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55908", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A27", sNSSAI_SD:"27", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55910", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A25", sNSSAI_SD:"25", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55912", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A23", sNSSAI_SD:"23", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55914", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N13/PlmnInfo:PLMNI-A21", sNSSAI_SD:"21", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55915", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A10", sNSSAI_SD:"10", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55917", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A8", sNSSAI_SD:"8", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55919", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A6", sNSSAI_SD:"6", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55916", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A9", sNSSAI_SD:"9", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55921", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A4", sNSSAI_SD:"4", plmn_mnc:"81"}}] AS row
CREATE (n:plmninfo{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/plmninfo/55918", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A7", sNSSAI_SD:"7", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55923", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A2", sNSSAI_SD:"2", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55925", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A0", sNSSAI_SD:"0", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55920", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A5", sNSSAI_SD:"5", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55927", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A29", sNSSAI_SD:"29", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55929", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A27", sNSSAI_SD:"27", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55931", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A25", sNSSAI_SD:"25", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55933", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A23", sNSSAI_SD:"23", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55922", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A3", sNSSAI_SD:"3", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55935", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A21", sNSSAI_SD:"21", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55924", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A1", sNSSAI_SD:"1", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55926", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A30", sNSSAI_SD:"30", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55928", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A28", sNSSAI_SD:"28", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55930", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A26", sNSSAI_SD:"26", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55932", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A24", sNSSAI_SD:"24", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/55934", properties:{sNSSAI_SST:"1", plmn_mcc:"808", name:"N14/PlmnInfo:PLMNI-A22", sNSSAI_SD:"22", plmn_mnc:"81"}}, {uuid:"ctw/plmninfo/45430", properties:{sNSSAI_SST:"1", plmn_mcc:"128", name:"N2009/PlmnInfo:PLMNI-A4", sNSSAI_SD:"10", plmn_mnc:"49"}}, {uuid:"ctw/plmninfo/45431", properties:{sNSSAI_SST:"1", plmn_mcc:"128", name:"N2009/PlmnInfo:PLMNI-A5", sNSSAI_SD:"11", plmn_mnc:"49"}}, {uuid:"ctw/plmninfo/45432", properties:{sNSSAI_SST:"1", plmn_mcc:"128", name:"N2009/PlmnInfo:PLMNI-A6", sNSSAI_SD:"10", plmn_mnc:"50"}}, {uuid:"ctw/plmninfo/45434", properties:{sNSSAI_SST:"1", plmn_mcc:"130", name:"N2009/PlmnInfo:PLMNI-A8", sNSSAI_SD:"10", plmn_mnc:"51"}}] AS row
CREATE (n:plmninfo{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/plmninfo/45433", properties:{sNSSAI_SST:"1", plmn_mcc:"128", name:"N2009/PlmnInfo:PLMNI-A7", sNSSAI_SD:"11", plmn_mnc:"49"}}, {uuid:"ctw/plmninfo/45435", properties:{sNSSAI_SST:"1", plmn_mcc:"130", name:"N2009/PlmnInfo:PLMNI-A9", sNSSAI_SD:"11", plmn_mnc:"51"}}] AS row
CREATE (n:plmninfo{uuid: row.uuid}) SET n += row.properties SET n:ctw:cmObject;
UNWIND [{uuid:"ctw/networkslice/21315", properties:{name:"NetworkSlice:NSI-A"}}, {uuid:"ctw/networkslice/21316", properties:{name:"NetworkSlice:NSI-B"}}, {uuid:"ctw/networkslice/21317", properties:{name:"NetworkSlice:NSI-C"}}, {uuid:"ctw/networkslice/285600", properties:{name:"N8/NetworkSlice:NSI-B1"}}, {uuid:"ctw/networkslice/285602", properties:{name:"N8/NetworkSlice:NSI-B3"}}, {uuid:"ctw/networkslice/285601", properties:{name:"N8/NetworkSlice:NSI-B2"}}, {uuid:"ctw/networkslice/285620", properties:{name:"N9/NetworkSlice:NSI-B1"}}, {uuid:"ctw/networkslice/285622", properties:{name:"N9/NetworkSlice:NSI-B3"}}, {uuid:"ctw/networkslice/285621", properties:{name:"N9/NetworkSlice:NSI-B2"}}, {uuid:"ctw/networkslice/285624", properties:{name:"N9/NetworkSlice:NSI-B5"}}, {uuid:"ctw/networkslice/285623", properties:{name:"N9/NetworkSlice:NSI-B4"}}, {uuid:"ctw/networkslice/285638", properties:{name:"N13/NetworkSlice:NSI-A"}}, {uuid:"ctw/networkslice/285658", properties:{name:"N14/NetworkSlice:NSI-A"}}] AS row
CREATE (n:networkslice{uuid: row.uuid}) SET n += row.properties SET n:ctw:logicalPartition;
UNWIND [{uuid:"ctg/geographicsite/1045", properties:{name:"GeographicSite:DataCenter1"}}, {uuid:"ctg/geographicsite/1046", properties:{name:"GeographicSite:DataCenter2"}}] AS row
CREATE (n:geographicsite{uuid: row.uuid}) SET n += row.properties SET n:ctg:topologyContainer;
UNWIND [{uuid:"ctw/serviceprofile/1662", properties:{name:"ServiceProfile:SP-B"}}, {uuid:"ctw/serviceprofile/1661", properties:{name:"ServiceProfile:SP-A"}}, {uuid:"ctw/serviceprofile/1663", properties:{name:"ServiceProfile:SP-C"}}, {uuid:"ctw/serviceprofile/21710", properties:{name:"N8/ServiceProfile:SP-B1"}}, {uuid:"ctw/serviceprofile/21711", properties:{name:"N8/ServiceProfile:SP-B2"}}, {uuid:"ctw/serviceprofile/21713", properties:{name:"N9/ServiceProfile:SP-B2"}}, {uuid:"ctw/serviceprofile/21712", properties:{name:"N9/ServiceProfile:SP-B1"}}, {uuid:"ctw/serviceprofile/21714", properties:{name:"N13/ServiceProfile:SP-A"}}, {uuid:"ctw/serviceprofile/21715", properties:{name:"N14/ServiceProfile:SP-A"}}] AS row
CREATE (n:serviceprofile{uuid: row.uuid}) SET n += row.properties SET n:ctw:profileObject;
UNWIND [{uuid:"ctw/amf/21329", properties:{ExternalRef_nodeFDN:"MeContext=PCC00011,ManagedElement=PCC00011", SOA_NF_nfFqdn:"pcc00011.sero.gic.ericsson.se", SOA_NF_applicationId:"PCC00011", name:"WirelessNetworkFunction:PCC00012-AMF", SOA_NF_oamIP:"10.120.130.12", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e7101"}}, {uuid:"ctw/amf/21328", properties:{ExternalRef_nodeFDN:"MeContext=PCC00010,ManagedElement=PCC00010", SOA_NF_nfFqdn:"pcc00010.sero.gic.ericsson.se", SOA_NF_applicationId:"PCC00010", name:"WirelessNetworkFunction:PCC00010-AMF", SOA_NF_oamIP:"10.120.130.10", SOA_NF_nfInstanceId:"07568e58-8b71-4c2c-ac47-9aafec5e710"}}] AS row
CREATE (n:amf{uuid: row.uuid}) SET n += row.properties SET n:ctw:wirelessNetworkFunction;
UNWIND [{uuid:"ctw/resourcepartitionmember/285612", properties:{name:"N8/ResourcePartitionMember:RPM-B2"}}, {uuid:"ctw/resourcepartitionmember/285614", properties:{name:"N8/ResourcePartitionMember:RPM-B4"}}, {uuid:"ctw/resourcepartitionmember/285611", properties:{name:"N8/ResourcePartitionMember:RPM-B1"}}, {uuid:"ctw/resourcepartitionmember/285613", properties:{name:"N8/ResourcePartitionMember:RPM-B3"}}, {uuid:"ctw/resourcepartitionmember/285633", properties:{name:"N9/ResourcePartitionMember:RPM-B1"}}, {uuid:"ctw/resourcepartitionmember/285634", properties:{name:"N9/ResourcePartitionMember:RPM-B2"}}, {uuid:"ctw/resourcepartitionmember/285642", properties:{name:"N13/ResourcePartitionMember:RPM-A1"}}, {uuid:"ctw/resourcepartitionmember/285644", properties:{name:"N13/ResourcePartitionMember:RPM-A3"}}, {uuid:"ctw/resourcepartitionmember/285646", properties:{name:"N13/ResourcePartitionMember:RPM-A5"}}, {uuid:"ctw/resourcepartitionmember/285643", properties:{name:"N13/ResourcePartitionMember:RPM-A2"}}, {uuid:"ctw/resourcepartitionmember/285645", properties:{name:"N13/ResourcePartitionMember:RPM-A4"}}, {uuid:"ctw/resourcepartitionmember/285663", properties:{name:"N14/ResourcePartitionMember:RPM-A2"}}, {uuid:"ctw/resourcepartitionmember/285665", properties:{name:"N14/ResourcePartitionMember:RPM-A4"}}, {uuid:"ctw/resourcepartitionmember/285662", properties:{name:"N14/ResourcePartitionMember:RPM-A1"}}, {uuid:"ctw/resourcepartitionmember/285664", properties:{name:"N14/ResourcePartitionMember:RPM-A3"}}, {uuid:"ctw/resourcepartitionmember/285666", properties:{name:"N14/ResourcePartitionMember:RPM-A5"}}] AS row
CREATE (n:resourcepartitionmember{uuid: row.uuid}) SET n += row.properties SET n:resource:ctw;
UNWIND [{uuid:"ctw/qosprofile/1007", properties:{name:"N8/QosProfile:QOSP-B2"}}, {uuid:"ctw/qosprofile/1006", properties:{name:"N8/QosProfile:QOSP-B1"}}, {uuid:"ctw/qosprofile/1008", properties:{name:"N9/QosProfile:QOSP-B1"}}, {uuid:"ctw/qosprofile/1009", properties:{name:"N9/QosProfile:QOSP-B2"}}, {uuid:"ctw/qosprofile/1010", properties:{name:"N13/QosProfile:QOSP-A"}}, {uuid:"ctw/qosprofile/1011", properties:{name:"N14/QosProfile:QOSP-A"}}, {uuid:"ctw/qosprofile/913", properties:{name:"NSS3212/QosProfile:QOSP-A"}}, {uuid:"ctw/qosprofile/619", properties:{name:"QOS64/QosProfile:QOSP-A"}}] AS row
CREATE (n:qosprofile{uuid: row.uuid}) SET n += row.properties SET n:ctw:profileObject;
:commit
:begin
UNWIND [{start: {uuid:"ctw/sliceprofile/3883"}, end: {uuid:"ctw/plmninfo/3828"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3883"}, end: {uuid:"ctw/plmninfo/3829"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3889"}, end: {uuid:"ctw/plmninfo/3832"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3889"}, end: {uuid:"ctw/plmninfo/3833"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3885"}, end: {uuid:"ctw/plmninfo/3830"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3885"}, end: {uuid:"ctw/plmninfo/3831"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3887"}, end: {uuid:"ctw/plmninfo/3832"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3887"}, end: {uuid:"ctw/plmninfo/3833"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3884"}, end: {uuid:"ctw/plmninfo/3828"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3884"}, end: {uuid:"ctw/plmninfo/3829"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3886"}, end: {uuid:"ctw/plmninfo/3830"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3886"}, end: {uuid:"ctw/plmninfo/3831"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3888"}, end: {uuid:"ctw/plmninfo/3832"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/3888"}, end: {uuid:"ctw/plmninfo/3833"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/52687"}, end: {uuid:"ctw/plmninfo/55887"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/52687"}, end: {uuid:"ctw/plmninfo/55889"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/52688"}, end: {uuid:"ctw/plmninfo/55886"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/52690"}, end: {uuid:"ctw/plmninfo/55890"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/52689"}, end: {uuid:"ctw/plmninfo/55891"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/sliceprofile/52689"}, end: {uuid:"ctw/plmninfo/55893"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:sliceprofile{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:SliceProfile_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/sliceprofile/52695"}, end: {uuid:"ctw/plmninfo/55895"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52696"}, end: {uuid:"ctw/plmninfo/55895"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52691"}, end: {uuid:"ctw/plmninfo/55898"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52698"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52699"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52700"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52697"}, end: {uuid:"ctw/plmninfo/55919"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52701"}, end: {uuid:"ctw/plmninfo/55916"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/sliceprofile/52702"}, end: {uuid:"ctw/plmninfo/55916"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:sliceprofile{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:SliceProfile_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/serviceprofile/1662"}, end: {uuid:"ctw/plmninfo/3830"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/1662"}, end: {uuid:"ctw/plmninfo/3831"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/1661"}, end: {uuid:"ctw/plmninfo/3828"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/1661"}, end: {uuid:"ctw/plmninfo/3829"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/1663"}, end: {uuid:"ctw/plmninfo/3832"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/1663"}, end: {uuid:"ctw/plmninfo/3833"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/21710"}, end: {uuid:"ctw/plmninfo/55887"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/21712"}, end: {uuid:"ctw/plmninfo/55891"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/serviceprofile/21714"}, end: {uuid:"ctw/plmninfo/55894"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/serviceprofile/21715"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:serviceprofile{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:serviceProfile_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/285603"}, end: {uuid:"ctw/qosprofile/1007"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285639"}, end: {uuid:"ctw/qosprofile/1010"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285641"}, end: {uuid:"ctw/qosprofile/1010"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285640"}, end: {uuid:"ctw/qosprofile/1010"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285660"}, end: {uuid:"ctw/qosprofile/1011"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285659"}, end: {uuid:"ctw/qosprofile/1011"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285661"}, end: {uuid:"ctw/qosprofile/1011"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285604"}, end: {uuid:"ctw/qosprofile/1007"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285606"}, end: {uuid:"ctw/qosprofile/1006"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285605"}, end: {uuid:"ctw/qosprofile/1006"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285626"}, end: {uuid:"ctw/qosprofile/1009"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285625"}, end: {uuid:"ctw/qosprofile/1009"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285627"}, end: {uuid:"ctw/qosprofile/1008"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285628"}, end: {uuid:"ctw/qosprofile/1008"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285629"}, end: {uuid:"ctw/qosprofile/1008"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:qosprofile{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnetsSupportQosProfiles]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslice/21315"}, end: {uuid:"ctw/serviceprofile/1661"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/21316"}, end: {uuid:"ctw/serviceprofile/1662"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/21317"}, end: {uuid:"ctw/serviceprofile/1663"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285600"}, end: {uuid:"ctw/serviceprofile/21710"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285620"}, end: {uuid:"ctw/serviceprofile/21712"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:networkslice{uuid: row.start.uuid})
MATCH (end:serviceprofile{uuid: row.end.uuid})
CREATE (start)-[r:networkSlice_to_requirement_serviceProfiles]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/qosprofile/1007"}, end: {uuid:"ctw/fiveqiset/3309"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/qosprofile/1006"}, end: {uuid:"ctw/fiveqiset/3305"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/qosprofile/1008"}, end: {uuid:"ctw/fiveqiset/3312"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/qosprofile/1009"}, end: {uuid:"ctw/fiveqiset/3316"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/qosprofile/1010"}, end: {uuid:"ctw/fiveqiset/3317"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/qosprofile/1011"}, end: {uuid:"ctw/fiveqiset/3320"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/qosprofile/619"}, end: {uuid:"ctw/fiveqiset/2143"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/qosprofile/619"}, end: {uuid:"ctw/fiveqiset/2142"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:qosprofile{uuid: row.start.uuid})
MATCH (end:fiveqiset{uuid: row.end.uuid})
CREATE (start)-[r:qosProfileHasFiveQISets]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctg/geographicsite/1045"}, end: {uuid:"ctw/smf/21330"}, properties:{abstractAssociation:"allocated"}}, {start: {uuid:"ctg/geographicsite/1046"}, end: {uuid:"ctw/smf/21331"}, properties:{abstractAssociation:"allocated"}}, {start: {uuid:"ctg/geographicsite/1046"}, end: {uuid:"ctw/smf/21332"}, properties:{abstractAssociation:"allocated"}}] AS row
MATCH (start:geographicsite{uuid: row.start.uuid})
MATCH (end:smf{uuid: row.end.uuid})
CREATE (start)-[r:wirelessNetFunction_to_site]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslice/21315"}, end: {uuid:"ctw/networkslicesubnet/21318"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/21317"}, end: {uuid:"ctw/networkslicesubnet/21320"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/21316"}, end: {uuid:"ctw/networkslicesubnet/21319"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/285601"}, end: {uuid:"ctw/networkslicesubnet/285606"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/285600"}, end: {uuid:"ctw/networkslicesubnet/285603"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/285620"}, end: {uuid:"ctw/networkslicesubnet/285625"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/285621"}, end: {uuid:"ctw/networkslicesubnet/285628"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslice/285623"}, end: {uuid:"ctw/networkslicesubnet/285629"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}] AS row
MATCH (start:networkslice{uuid: row.start.uuid})
MATCH (end:networkslicesubnet{uuid: row.end.uuid})
CREATE (start)-[r:networkSlice_to_networkSliceSubnet]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/resourcepartition/285608"}, end: {uuid:"ctw/resourcepartitionmember/285612"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285610"}, end: {uuid:"ctw/resourcepartitionmember/285614"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285607"}, end: {uuid:"ctw/resourcepartitionmember/285611"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285609"}, end: {uuid:"ctw/resourcepartitionmember/285613"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285631"}, end: {uuid:"ctw/resourcepartitionmember/285633"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285632"}, end: {uuid:"ctw/resourcepartitionmember/285634"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285648"}, end: {uuid:"ctw/resourcepartitionmember/285642"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285650"}, end: {uuid:"ctw/resourcepartitionmember/285644"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285652"}, end: {uuid:"ctw/resourcepartitionmember/285646"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285649"}, end: {uuid:"ctw/resourcepartitionmember/285643"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285651"}, end: {uuid:"ctw/resourcepartitionmember/285645"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285669"}, end: {uuid:"ctw/resourcepartitionmember/285663"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285671"}, end: {uuid:"ctw/resourcepartitionmember/285665"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285668"}, end: {uuid:"ctw/resourcepartitionmember/285662"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285670"}, end: {uuid:"ctw/resourcepartitionmember/285664"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartition/285672"}, end: {uuid:"ctw/resourcepartitionmember/285666"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:resourcepartition{uuid: row.start.uuid})
MATCH (end:resourcepartitionmember{uuid: row.end.uuid})
CREATE (start)-[r:rsrcPartition_to_rsrcPartitionMbr]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/285603"}, end: {uuid:"ctw/nrcell/285599"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285626"}, end: {uuid:"ctw/nrcell/285619"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285625"}, end: {uuid:"ctw/nrcell/285619"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285639"}, end: {uuid:"ctw/nrcell/285636"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285641"}, end: {uuid:"ctw/nrcell/285636"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285640"}, end: {uuid:"ctw/nrcell/285636"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285660"}, end: {uuid:"ctw/nrcell/285656"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285659"}, end: {uuid:"ctw/nrcell/285656"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285661"}, end: {uuid:"ctw/nrcell/285656"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslicesubnet/285604"}, end: {uuid:"ctw/nrcell/285599"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:nrcell{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnet_to_nrCell]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/fiveqiset/3306"}, end: {uuid:"ctw/fiveqiflow/8047"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8057"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8058"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8059"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8060"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8061"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8062"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8064"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3310"}, end: {uuid:"ctw/fiveqiflow/8068"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8063"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3308"}, end: {uuid:"ctw/fiveqiflow/8065"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3310"}, end: {uuid:"ctw/fiveqiflow/8067"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3305"}, end: {uuid:"ctw/fiveqiflow/8046"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3305"}, end: {uuid:"ctw/fiveqiflow/8045"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8055"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8056"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8048"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8049"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8050"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8051"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:fiveqiset{uuid: row.start.uuid})
MATCH (end:fiveqiflow{uuid: row.end.uuid})
CREATE (start)-[r:fiveQISetContainsFiveQIFlows]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8052"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8053"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3307"}, end: {uuid:"ctw/fiveqiflow/8054"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3309"}, end: {uuid:"ctw/fiveqiflow/8066"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3311"}, end: {uuid:"ctw/fiveqiflow/8069"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3311"}, end: {uuid:"ctw/fiveqiflow/8070"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3313"}, end: {uuid:"ctw/fiveqiflow/8073"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3312"}, end: {uuid:"ctw/fiveqiflow/8072"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3312"}, end: {uuid:"ctw/fiveqiflow/8071"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8083"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8084"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8085"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8086"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8087"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8088"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8089"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8090"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3315"}, end: {uuid:"ctw/fiveqiflow/8091"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8081"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8082"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:fiveqiset{uuid: row.start.uuid})
MATCH (end:fiveqiflow{uuid: row.end.uuid})
CREATE (start)-[r:fiveQISetContainsFiveQIFlows]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8074"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8075"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8076"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8077"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8078"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8079"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3314"}, end: {uuid:"ctw/fiveqiflow/8080"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3316"}, end: {uuid:"ctw/fiveqiflow/8092"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3318"}, end: {uuid:"ctw/fiveqiflow/8095"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3318"}, end: {uuid:"ctw/fiveqiflow/8096"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3317"}, end: {uuid:"ctw/fiveqiflow/8093"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3317"}, end: {uuid:"ctw/fiveqiflow/8094"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3319"}, end: {uuid:"ctw/fiveqiflow/8097"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3319"}, end: {uuid:"ctw/fiveqiflow/8098"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3320"}, end: {uuid:"ctw/fiveqiflow/8099"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3320"}, end: {uuid:"ctw/fiveqiflow/8100"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3322"}, end: {uuid:"ctw/fiveqiflow/8103"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3322"}, end: {uuid:"ctw/fiveqiflow/8104"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3321"}, end: {uuid:"ctw/fiveqiflow/8101"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3321"}, end: {uuid:"ctw/fiveqiflow/8102"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:fiveqiset{uuid: row.start.uuid})
MATCH (end:fiveqiflow{uuid: row.end.uuid})
CREATE (start)-[r:fiveQISetContainsFiveQIFlows]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/fiveqiset/2143"}, end: {uuid:"ctw/fiveqiflow/5034"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/2142"}, end: {uuid:"ctw/fiveqiflow/5033"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:fiveqiset{uuid: row.start.uuid})
MATCH (end:fiveqiflow{uuid: row.end.uuid})
CREATE (start)-[r:fiveQISetContainsFiveQIFlows]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/nrcell/285599"}, end: {uuid:"ctw/plmninfo/55887"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/nrcell/285599"}, end: {uuid:"ctw/plmninfo/55889"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/nrcell/285599"}, end: {uuid:"ctw/plmninfo/55886"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285599"}, end: {uuid:"ctw/plmninfo/55888"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285619"}, end: {uuid:"ctw/plmninfo/55890"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285619"}, end: {uuid:"ctw/plmninfo/55891"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285619"}, end: {uuid:"ctw/plmninfo/55892"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285619"}, end: {uuid:"ctw/plmninfo/55893"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55895"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55897"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55894"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55899"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55896"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55901"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55898"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55903"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55900"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55905"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55907"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55902"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:nrcell{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:nrCell_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55909"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55904"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55911"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55906"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55913"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55908"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55910"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55912"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285636"}, end: {uuid:"ctw/plmninfo/55914"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55917"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55919"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55916"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55921"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55918"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55923"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55925"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55920"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55927"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55929"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:nrcell{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:nrCell_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55931"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55933"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55922"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55935"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55924"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55926"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55928"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55930"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55932"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/285656"}, end: {uuid:"ctw/plmninfo/55934"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/251524"}, end: {uuid:"ctw/plmninfo/45430"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/251524"}, end: {uuid:"ctw/plmninfo/45431"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/251524"}, end: {uuid:"ctw/plmninfo/45432"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/251524"}, end: {uuid:"ctw/plmninfo/45434"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/251524"}, end: {uuid:"ctw/plmninfo/45433"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/nrcell/251524"}, end: {uuid:"ctw/plmninfo/45435"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:nrcell{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:nrCell_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/gnbdu/285598"}, end: {uuid:"ctw/fiveqiset/3306"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285598"}, end: {uuid:"ctw/fiveqiset/3308"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285598"}, end: {uuid:"ctw/fiveqiset/3305"}, properties:{abstractAssociation:"cmObjectHasWnf"}}, {start: {uuid:"ctw/gnbdu/285598"}, end: {uuid:"ctw/fiveqiset/3307"}, properties:{abstractAssociation:"cmObjectHasWnf"}}, {start: {uuid:"ctw/gnbdu/285598"}, end: {uuid:"ctw/fiveqiset/3309"}, properties:{abstractAssociation:"cmObjectHasWnf"}}, {start: {uuid:"ctw/gnbdu/285618"}, end: {uuid:"ctw/fiveqiset/3312"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285618"}, end: {uuid:"ctw/fiveqiset/3313"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285618"}, end: {uuid:"ctw/fiveqiset/3314"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285618"}, end: {uuid:"ctw/fiveqiset/3315"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285618"}, end: {uuid:"ctw/fiveqiset/3316"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/gnbdu/285637"}, end: {uuid:"ctw/fiveqiset/3317"}, properties:{abstractAssociation:"cmObjectHasWnf"}}, {start: {uuid:"ctw/gnbdu/285657"}, end: {uuid:"ctw/fiveqiset/3320"}, properties:{abstractAssociation:"cmObjectHasWnf"}}] AS row
MATCH (start:gnbdu{uuid: row.start.uuid})
MATCH (end:fiveqiset{uuid: row.end.uuid})
CREATE (start)-[r:wirelessNetworkFunctionHas5QISets]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctg/geographicsite/1046"}, end: {uuid:"ctw/amf/21329"}, properties:{abstractAssociation:"allocated"}}, {start: {uuid:"ctg/geographicsite/1045"}, end: {uuid:"ctw/amf/21328"}, properties:{abstractAssociation:"allocated"}}] AS row
MATCH (start:geographicsite{uuid: row.start.uuid})
MATCH (end:amf{uuid: row.end.uuid})
CREATE (start)-[r:wirelessNetFunction_to_site]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslice/285600"}, end: {uuid:"ctw/nrcell/285599"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/networkslice/285620"}, end: {uuid:"ctw/nrcell/285619"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:networkslice{uuid: row.start.uuid})
MATCH (end:nrcell{uuid: row.end.uuid})
CREATE (start)-[r:networkSlice_to_nrCell]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/21322"}, end: {uuid:"ctw/smf/21330"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}, {start: {uuid:"ctw/networkslicesubnet/21324"}, end: {uuid:"ctw/smf/21331"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}, {start: {uuid:"ctw/networkslicesubnet/21326"}, end: {uuid:"ctw/smf/21332"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:smf{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnets_to_wirelessNetFunction]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/21321"}, end: {uuid:"ctw/amf/21328"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}, {start: {uuid:"ctw/networkslicesubnet/21323"}, end: {uuid:"ctw/amf/21328"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}, {start: {uuid:"ctw/networkslicesubnet/21325"}, end: {uuid:"ctw/amf/21329"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:amf{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnets_to_wirelessNetFunction]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslice/285658"}, end: {uuid:"ctw/serviceprofile/21715"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285602"}, end: {uuid:"ctw/serviceprofile/21710"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285601"}, end: {uuid:"ctw/serviceprofile/21711"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285622"}, end: {uuid:"ctw/serviceprofile/21712"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285621"}, end: {uuid:"ctw/serviceprofile/21713"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslice/285638"}, end: {uuid:"ctw/serviceprofile/21714"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:networkslice{uuid: row.start.uuid})
MATCH (end:serviceprofile{uuid: row.end.uuid})
CREATE (start)-[r:networkSlice_to_capability_serviceProfile]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctg/geographicsite/1045"}, end: {uuid:"ctw/upf/21333"}, properties:{abstractAssociation:"allocated"}}, {start: {uuid:"ctg/geographicsite/1046"}, end: {uuid:"ctw/upf/21335"}, properties:{abstractAssociation:"allocated"}}, {start: {uuid:"ctg/geographicsite/1046"}, end: {uuid:"ctw/upf/21334"}, properties:{abstractAssociation:"allocated"}}] AS row
MATCH (start:geographicsite{uuid: row.start.uuid})
MATCH (end:upf{uuid: row.end.uuid})
CREATE (start)-[r:wirelessNetFunction_to_site]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/resourcepartitionset/285616"}, end: {uuid:"ctw/resourcepartition/285609"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285615"}, end: {uuid:"ctw/resourcepartition/285607"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285615"}, end: {uuid:"ctw/resourcepartition/285608"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285617"}, end: {uuid:"ctw/resourcepartition/285610"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285635"}, end: {uuid:"ctw/resourcepartition/285631"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285635"}, end: {uuid:"ctw/resourcepartition/285632"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285654"}, end: {uuid:"ctw/resourcepartition/285650"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285654"}, end: {uuid:"ctw/resourcepartition/285652"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285653"}, end: {uuid:"ctw/resourcepartition/285648"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285653"}, end: {uuid:"ctw/resourcepartition/285651"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285655"}, end: {uuid:"ctw/resourcepartition/285649"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285673"}, end: {uuid:"ctw/resourcepartition/285671"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285675"}, end: {uuid:"ctw/resourcepartition/285669"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285674"}, end: {uuid:"ctw/resourcepartition/285670"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/resourcepartitionset/285674"}, end: {uuid:"ctw/resourcepartition/285672"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:resourcepartitionset{uuid: row.start.uuid})
MATCH (end:resourcepartition{uuid: row.end.uuid})
CREATE (start)-[r:rsrcPartitionSet_to_rsrcPartition]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctg/geographicsite/1045"}, end: {uuid:"ctv/cismcluster/21313"}, properties:{abstractAssociation:"runsOnContainer"}}, {start: {uuid:"ctg/geographicsite/1046"}, end: {uuid:"ctv/cismcluster/21314"}, properties:{abstractAssociation:"runsOnContainer"}}] AS row
MATCH (start:geographicsite{uuid: row.start.uuid})
MATCH (end:cismcluster{uuid: row.end.uuid})
CREATE (start)-[r:cismCluster_to_site]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/21326"}, end: {uuid:"ctw/sliceprofile/3888"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/21321"}, end: {uuid:"ctw/sliceprofile/3883"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/21321"}, end: {uuid:"ctw/sliceprofile/3884"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/21323"}, end: {uuid:"ctw/sliceprofile/3885"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/21323"}, end: {uuid:"ctw/sliceprofile/3886"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/21325"}, end: {uuid:"ctw/sliceprofile/3887"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/21327"}, end: {uuid:"ctw/sliceprofile/3889"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285603"}, end: {uuid:"ctw/sliceprofile/52687"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285641"}, end: {uuid:"ctw/sliceprofile/52695"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285640"}, end: {uuid:"ctw/sliceprofile/52693"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285660"}, end: {uuid:"ctw/sliceprofile/52699"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285661"}, end: {uuid:"ctw/sliceprofile/52701"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285604"}, end: {uuid:"ctw/sliceprofile/52688"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285626"}, end: {uuid:"ctw/sliceprofile/52690"}, properties:{abstractAssociation:"hasProfile"}}, {start: {uuid:"ctw/networkslicesubnet/285625"}, end: {uuid:"ctw/sliceprofile/52689"}, properties:{abstractAssociation:"hasProfile"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:sliceprofile{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnet_to_requirement_sliceProfile]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/fiveqiset/3309"}, end: {uuid:"ctw/resourcepartition/285608"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/fiveqiset/3311"}, end: {uuid:"ctw/resourcepartition/285610"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/fiveqiset/3305"}, end: {uuid:"ctw/resourcepartition/285607"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3310"}, end: {uuid:"ctw/resourcepartition/285609"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3312"}, end: {uuid:"ctw/resourcepartition/285631"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3316"}, end: {uuid:"ctw/resourcepartition/285632"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3317"}, end: {uuid:"ctw/resourcepartition/285648"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3319"}, end: {uuid:"ctw/resourcepartition/285650"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3319"}, end: {uuid:"ctw/resourcepartition/285652"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3317"}, end: {uuid:"ctw/resourcepartition/285647"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3318"}, end: {uuid:"ctw/resourcepartition/285649"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3317"}, end: {uuid:"ctw/resourcepartition/285651"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3320"}, end: {uuid:"ctw/resourcepartition/285667"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3321"}, end: {uuid:"ctw/resourcepartition/285669"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3320"}, end: {uuid:"ctw/resourcepartition/285671"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3320"}, end: {uuid:"ctw/resourcepartition/285668"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3322"}, end: {uuid:"ctw/resourcepartition/285670"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/fiveqiset/3322"}, end: {uuid:"ctw/resourcepartition/285672"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:fiveqiset{uuid: row.start.uuid})
MATCH (end:resourcepartition{uuid: row.end.uuid})
CREATE (start)-[r:fiveQISet_to_rsrcPartition]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/resourcepartitionmember/285612"}, end: {uuid:"ctw/plmninfo/55887"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285614"}, end: {uuid:"ctw/plmninfo/55889"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285611"}, end: {uuid:"ctw/plmninfo/55886"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285613"}, end: {uuid:"ctw/plmninfo/55889"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285633"}, end: {uuid:"ctw/plmninfo/55890"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285634"}, end: {uuid:"ctw/plmninfo/55891"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285642"}, end: {uuid:"ctw/plmninfo/55894"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285644"}, end: {uuid:"ctw/plmninfo/55894"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285646"}, end: {uuid:"ctw/plmninfo/55895"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285643"}, end: {uuid:"ctw/plmninfo/55894"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285645"}, end: {uuid:"ctw/plmninfo/55895"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285663"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285665"}, end: {uuid:"ctw/plmninfo/55916"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285662"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285664"}, end: {uuid:"ctw/plmninfo/55915"}, properties:{abstractAssociation:"hasCmObject"}}, {start: {uuid:"ctw/resourcepartitionmember/285666"}, end: {uuid:"ctw/plmninfo/55916"}, properties:{abstractAssociation:"hasCmObject"}}] AS row
MATCH (start:resourcepartitionmember{uuid: row.start.uuid})
MATCH (end:plmninfo{uuid: row.end.uuid})
CREATE (start)-[r:rsrcPartitionMem_to_plmnInfo]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/21318"}, end: {uuid:"ctw/networkslicesubnet/21322"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslicesubnet/21320"}, end: {uuid:"ctw/networkslicesubnet/21326"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslicesubnet/21319"}, end: {uuid:"ctw/networkslicesubnet/21324"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslicesubnet/21318"}, end: {uuid:"ctw/networkslicesubnet/21321"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslicesubnet/21319"}, end: {uuid:"ctw/networkslicesubnet/21323"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslicesubnet/21320"}, end: {uuid:"ctw/networkslicesubnet/21325"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}, {start: {uuid:"ctw/networkslicesubnet/21320"}, end: {uuid:"ctw/networkslicesubnet/21327"}, properties:{abstractAssociation:"encompassesLogicalPartitions"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:networkslicesubnet{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnet_to_networkSliceSubnet]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/networkslicesubnet/21322"}, end: {uuid:"ctw/upf/21333"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}, {start: {uuid:"ctw/networkslicesubnet/21324"}, end: {uuid:"ctw/upf/21334"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}, {start: {uuid:"ctw/networkslicesubnet/21327"}, end: {uuid:"ctw/upf/21335"}, properties:{abstractAssociation:"encompassesWirelessNetFunctions"}}] AS row
MATCH (start:networkslicesubnet{uuid: row.start.uuid})
MATCH (end:upf{uuid: row.end.uuid})
CREATE (start)-[r:networkSliceSubnets_to_wirelessNetFunction]->(end) SET r += row.properties;
UNWIND [{start: {uuid:"ctw/gnbdu/285637"}, end: {uuid:"ctw/nrcell/285636"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/gnbdu/285657"}, end: {uuid:"ctw/nrcell/285656"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/gnbdu/285598"}, end: {uuid:"ctw/nrcell/285599"}, properties:{abstractAssociation:"hasResource"}}, {start: {uuid:"ctw/gnbdu/285618"}, end: {uuid:"ctw/nrcell/285619"}, properties:{abstractAssociation:"hasResource"}}] AS row
MATCH (start:gnbdu{uuid: row.start.uuid})
MATCH (end:nrcell{uuid: row.end.uuid})
CREATE (start)-[r:nrCells_to_gnbdu]->(end) SET r += row.properties;
:commit
